algo: muzero
device: cpu
eval:
  games: 100
  opponent: alphabeta
  opponent_depth: 7
logging:
  ckpt_dir: artifacts/released
  save_every_iters: 5
  tensorboard: artifacts/tensorboard/muzero_fast
mcts:
  c_puct: 2.5
  simulations: 200
  value_discount: 1.0
model:
  channels: 64
  latent_dim: 96
  res_blocks: 4
  unroll_steps: 3
seed: 42
self_play:
  dirichlet_alpha: 0.3
  dirichlet_eps: 0.25
  games_per_iter: 20
  max_moves: 42
  temperature_moves: 8
train:
  amp: true
  batch_size: 192
  epochs_per_iter: 20
  grad_clip: 1.0
  lr: 0.0015
  replay_capacity: 75000
  warm_start_steps: 2048
  weight_decay: 5.0e-05
