algo: muzero
seed: 42
device: cpu
self_play:
  games_per_iter: 10
  max_moves: 42
  temperature_moves: 6
  dirichlet_alpha: 0.3
  dirichlet_eps: 0.25
mcts:
  simulations: 100
  c_puct: 2.5
  value_discount: 1.0
model:
  channels: 64
  res_blocks: 3
  latent_dim: 64
  unroll_steps: 3
train:
  batch_size: 128
  lr: 0.001
  weight_decay: 0.0001
  grad_clip: 1.0
  epochs_per_iter: 10
  replay_capacity: 5000
  warm_start_steps: 1024
  amp: false
  policy_weight: 1.0
  value_weight: 1.0
  reward_weight: 0.5
logging:
  tensorboard: artifacts/tensorboard/muzero_debug
  ckpt_dir: artifacts/released
  save_every_iters: 1
eval:
  games: 50
  opponent: alphabeta
  opponent_depth: 5
