algo: ppo
seed: 0
timesteps: 200000
num_envs: 2
eval_games: 60
tensorboard_log: artifacts/tensorboard/selfplay
save_path: artifacts/released/ppo_selfplay_latest.zip
opponent: random
random_first_player: true
swap_start_probability: 0.5
self_play: true
self_play_update_interval: 25000
self_play_pool_size: 6
self_play_warmup_steps: 20000
self_play_deterministic_snapshots: false
reset_num_timesteps: true
rewards:
  win: 1.0
  loss: -1.0
  draw: 0.1
  invalid_move: -1.5
  step: -0.01
